puts "PROJECT EULER".center(60)
puts
puts "Problem 1: " + "Multiples".rjust(20)
puts
puts "This outputs the sum of all the multiples of two specified Numbers."
puts "for example 1 - 2, 3 - 5, etc."
puts "up till a range of your choosing, eg. (1, 100, 1000 or more). "
puts
puts "please input your first number"
fRange = gets.chomp.to_i
puts
puts "please enter your second number"
sRange = gets.chomp.to_i
puts
puts "Up till what range?"
range = gets.chomp.to_i

sum = 0
i = 0

answer = []

range.times do
  i = i + 1
  if i % fRange == 0 or i % sRange == 0 then
    sum = sum + i
  end
  # answer.push sum
end
puts
puts "Below is the sum of the multiples of #{fRange} and #{sRange} up \
till #{range}"
puts sum
# puts answer.inspect


# => problem 1 ends here
# => now unto the second euler Problem
#
#
#
puts
5.times do
  puts "..."
end
puts

a = 0
b = 1
c = 1
fiboSum = 0
fiboArray = []


puts "Problem 2: " + "Even Fibonacci Numbers".rjust(20)
puts
puts "Each new term in the Fibonacci sequence is generated by adding"
puts "The Previous two terms. By starting 1 & 2, the first ten terms would be"
puts "(1, 2, 3, 5, 8, 13, 21, 34, 55, 89)"
puts "By considering the terms in the Fibonacci sequence whose value do not"
puts "Exceed a value of your choosing, this program would output the sum of\
 the even valued terms"
puts
puts "What is your choosen value?"
choose = gets.chomp.to_i

while c <= choose
  c = a + b
  a = b
  b = c
  # fiboArray.push a
  fiboArray.push b
  # if c % 2 === 0
  #   fiboSum = fiboSum + c
  # end
end

fiboArray.length.times do |x|
  fiboSum = fiboSum + fiboArray[x]
end
puts
puts "Below is the Fibonacci sequence for your choosen range"
puts fiboArray.inspect
puts
puts "And the sum of the Fibonacci sequence is: "
puts fiboSum
